use_frameworks!

platform :ios, '13.0'

target 'JXCommonTools_Example' do
  pod 'JXCommonTools', :path => '../'
  pod 'SnapKit'

  target 'JXCommonTools_Tests' do
    inherit! :search_paths

    
  end
end
